#!/bin/bash

firstrun ()
{
	chown mysql -R /data
	cp -rf /var/lib/mysql/* /data/
	ZK_CLIENT_PORT=${ZK_CLIENT_PORT:-"2181"}
}

main() {

	if [[ ! -f /data/debian-10.0.flag ]]
	then
		firstrun

	else

		case "$MODE" in
			new)
				echo "Starting master"
				exec /usr/bin/mysqld_safe --wsrep-new-cluster
				;;
			node)
				echo "Starting node"
				exec /usr/bin/mysqld_safe
				;;
			restart_cluster)
				echo "Restarting cluster."
				echo "Run this command only on one node"
				exec /usr/bin/mysqld_safe --wsrep-cluster-address=gcomm://
				;;
			*)
				echo "Set envvar to your container <master|node>"
		esac
	fi
}

main $@

